export const CERTS = [
  { name: "Certified Ethical Hacker (CEH)", issuer: "LinkedIn Learning Community", category: "Security" },
  { name: "Six Sigma Green Belt (CSSGB)", issuer: "IIBA", category: "Management" },
  { name: "Lean Six Sigma Foundation", issuer: "Project Management Institute", category: "Management" },
  { name: "Administrative Human Resource", issuer: "HRCI", category: "HR" },
  { name: "Data-Driven HR: AI-Powered People Analytics", issuer: "SHRM", category: "HR" },
  { name: "Program Management for IT Professionals", issuer: "CompTIA", category: "Management" },
  { name: "Human Resource: Managing Employee Problems", issuer: "NASBA", category: "HR" },
  { name: "Atlassian Agile Project Management Professional Certificate", issuer: "Atlassian", category: "Management" },
  { name: "ServiceNow IT Leadership Professional Certificate", issuer: "ServiceNow", category: "Management" },
  { name: "Advance Certificate Course in Procurement Management", issuer: "SPESSECE-ABU", category: "Governance" },
  { name: "Advanced Procurement Management", issuer: "UNILAG", category: "Governance" },
  { name: "Advanced Procurement Management", issuer: "University of Benin", category: "Governance" },
  { name: "Education in Emergencies: Global Course", issuer: "UNICEF", category: "Governance" },
  { name: "Designing and Implementing Monitoring & Evaluation Systems", issuer: "Aga Khan Foundation", category: "Governance" },
  { name: "Sustainable Social Development Studies", issuer: "SPESSECE-ABU", category: "Governance" },
  { name: "Child Rights and why they matter", issuer: "UNICEF", category: "Governance" },
  { name: "Child Protection Systems Strengthening", issuer: "UNICEF", category: "Governance" },
  { name: "Elements of Environmental And Social Management Systems (ESMS)", issuer: "The World Bank", category: "Governance" },
  { name: "Environmental and Social Framework Fundamentals", issuer: "The World Bank Group", category: "Governance" },
  { name: "Sustainable Environmental Studies", issuer: "SPESSECE-ABU", category: "Governance" },
  { name: "Procurement Management", issuer: "SPESSECE-ABU", category: "Governance" },
  { name: "Generative AI", issuer: "LinkedIn", category: "AI" },
  { name: "Intensive Training in Product Management", issuer: "UK-Nigeria Tech Hub", category: "Management" },
  { name: "Getting Started with ChatGPT-4", issuer: "Great Learning Support", category: "AI" },
  { name: "Creative Certification Exam", issuer: "Google Career Certificates", category: "Data" },
  { name: "Search Ads 360 Certification Exam", issuer: "Google Digital Academy (Skillshop)", category: "Data" },
  { name: "Google Analytics Individual Qualification", issuer: "Google", category: "Data" },
  { name: "Google Analytics Certification", issuer: "Skillshop", category: "Data" },
  { name: "Excel Fundamentals - Formulas for Finance", issuer: "Corporate Finance Institute (CFI)", category: "Data" },
  { name: "Fundamentals of Digital Marketing", issuer: "Google Digital Skills For Africa", category: "Data" },
  { name: "Advancing Technology Based Learning in Nigeria", issuer: "Nigeria Computer Society", category: "Management" },
  { name: "Affiliate Marketing", issuer: "LinkedIn", category: "Data" },
  { name: "Affiliate Marketing Foundations", issuer: "LinkedIn", category: "Data" },
  { name: "Leading with Emotional Intelligence", issuer: "LinkedIn", category: "HR" },
  { name: "Networking Academy Learn-A-Thon 2021", issuer: "Cisco", category: "Security" },
  { name: "Master In-Demand Professional Soft Skills", issuer: "LinkedIn", category: "Management" },
  { name: "Bystander Training: From Bystander to Upstander", issuer: "LinkedIn", category: "HR" },
  { name: "Leading in Crisis", issuer: "LinkedIn", category: "Management" },
  { name: "Critical Thinking for Better Judgment and Decision-Making", issuer: "LinkedIn", category: "Management" },
  { name: "How to Engage Meaningfully in Allyship and Anti-Racism", issuer: "LinkedIn", category: "HR" },
  { name: "Cybersecurity Introduction", issuer: "IBM Digital Nation Africa, Kenyatta University", category: "Security" },
  { name: "Artificial Intelligence Introduction", issuer: "IBM Digital Nation Africa, Kenyatta University", category: "AI" },
  { name: "Data Science and Analytics", issuer: "IBM Digital Nation Africa, Kenyatta University", category: "Data" },
  { name: "Quantum Computing Introduction", issuer: "IBM Digital Nation Africa, Kenyatta University", category: "AI" },
];
